### ISSUE TITLE
The quotes were in the book for a reason

### ISSUE THREAD

**Issue by Kixunil** [ontes/superstition#1]
The author uses the quotes because he argues the things in quotes don't really exist, only some people believe they do. It's a deliberate choice and should be preserved to convey the authors intention properly.

**Comment by ontes** [comment]
The quotes were removed only from expressions where the nonexistence of government and authority were already implied (namely expressions like "the belief in government", "the myth of authority" etc.).  This made the text easier to read and the automatic translation was requiring way less manual fixes. The original text is still included in the file `superstition-orig.md`.

**Comment by Kixunil** [comment]
OK, that does seem to make sense.
